//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3QM.RunApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H3QM.RunApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xњнZ{tЕyяfwvпоиJ2odSћЖјmЅ        ///)#АјЬґ!њ$@’жhhy„4Н}IчJ¶…!¤”IЪћ°дA е@’&amp;9INЪ&amp;‡4        ///Р&amp;н‘_’-Й–ьў)Фo^»Я®®ђя№kлЮ™№{gїщж›Яч›№їаhуЗрfffѕ83sэМLзММ`Гб—|жзЪЇm?в[cѕъѓЇвзм “±эSЯ|о–&apos;¶b9`O¶нъй…Пь;ШлЖЦ*~Ъ¶ыМN{ЛxV_ЭцHЯЕ%,wЯУЩюќН}—\ІвЦ&lt;VсЩь`1Р№вЩюNївмJї¶н:]Ѕ®X6phые#Xо»д¶шћ¶=Oµн:xЩkУm»чалMЗЏОМјЮ¶kукЫ/Р7¬ѕ]ціъ3—№°ҐrНфgп ©ћ‚ФuА‰Єp(@3А1ґэ–ЫЯч _Щ/ЋёнЃSЪvЯqЫЗµн.ґн^°lд{тSV‹пьоЈПД–ґноnЇ]¬Лс=ъ¶WЗ;ъ.X0^ZХ‰7и!«	Z¬§©xгfЂkq.юкћEнЏЯюшAкf]w|aAR№v&gt;ФјЦї&lt;5(†ПmЫ}‘tйЛ§J—&gt;Њ.E{ЪїюЂщ®5ышveVСОЁ	а/e«ќG9(п9Щ­|нy№µѕUNЫ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ADAG {
            get {
                return ResourceManager.GetString("ADAG", resourceCulture);
            }
        }
    }
}
